### ISSUE TITLE
A bit map has been load you cant load another bit map 解決

### ISSUE THREAD

**Issue by ntut-feng** [steven989879/111_2_OOP#7]
在遊戲運行中，想按照練習中的蜜蜂那樣做出動畫，但是在宣告時，若是像
![image](https://user-images.githubusercontent.com/126550515/223736385-678f92bd-2eea-4a1f-83b4-46fcc73264a4.png)
的話便會顯示A bit map has been load you cant load another bit map
![image](https://user-images.githubusercontent.com/126550515/223736737-e061bd79-c813-40c1-99e7-a8375877759b.png)
但如果將宣告改為
![image](https://user-images.githubusercontent.com/126550515/223736884-01ad2322-8e37-4353-8c70-c87f687f1bbd.png)
便能成功執行，可是這樣就做不出動畫效果，想問助教遇到這種問題如何解決

**Comment by ntut-xuan** [comment]
你的框架版本是多少呢？

**Comment by ntut-feng** [comment]
> 版本為2017

**Comment by ntut-xuan** [comment]
我想詢問的是框架版本（v1.0.0 或更新），不是 VS 的版本

**Comment by ntut-feng** [comment]
> 我想詢問的是框架版本（v1.0.0 或更新），不是 VS 的版本

![image](https://user-images.githubusercontent.com/126550515/223925657-05602111-de47-46b6-a4d4-6e578ad760aa.png)
v4.8.04

**Comment by ntut-feng** [comment]
> > 我想詢問的是框架版本（v1.0.0 或更新），不是 VS 的版本
> 
> ![image](https://user-images.githubusercontent.com/126550515/223925657-05602111-de47-46b6-a4d4-6e578ad760aa.png) v4.8.04

![image](https://user-images.githubusercontent.com/126550515/223926585-43545933-0bb9-4647-bef4-b86a55b01bc9.png)
![image](https://user-images.githubusercontent.com/126550515/223926600-ce9436d4-49c2-4a3c-9ffb-6fffb2264e5e.png)

**Comment by ntut-xuan** [comment]
我指的是，LGF框架的版本。
如果你從來都沒有更新，那就是1.0.0
如果有的話，那就是1.1.0、1.1.2 或之類的

**Comment by ntut-feng** [comment]
> 我指的是，LGF框架的版本。 如果你從來都沒有更新，那就是1.0.0 如果有的話，那就是1.1.0、1.1.2 或之類的
我應該是沒有更新過
想問一下查詢方法是先開啟專案，在檔案中的game右鍵開啟屬性嗎
![image](https://user-images.githubusercontent.com/126550515/223928131-bd252c5f-3e2a-424a-9810-c1215d37ffb5.png)

**Comment by ntut-xuan** [comment]
你之前有更新過框架嗎？

**Comment by ntut-feng** [comment]
> 你之前有更新過框架嗎？

沒有

**Comment by ntut-xuan** [comment]
那就預設你是使用 v1.0.0 版本的框架，這個問題似乎在 v1.1.0 時被解決了，再請你將框架更新至 v1.1.0

**Comment by ntut-feng** [comment]
好的謝謝助教 剛剛試可以了
